# Generated by Django 2.2.10 on 2020-09-18 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200917_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
    ]
